[JBPM-9737] Conscious Language initiative (jBPM)
kiegroup/jbpm-work-items pull request #193
Opened 2021-05-17 10:41 UTC by fjtirado

Removing master

**JIRA**:

[link](https://issues.redhat.com/browse/JBPM-9737)

2021-05-27 13:19 UTC, mareknovotny commented
what about other occurrences?
 like https://github.com/kiegroup/jbpm-work-items/search?q=master

2021-05-27 13:25 UTC, mareknovotny requested changes
please change everything like the branch and dependencies are ready to go without offended names/terms.

2021-05-31 09:15 UTC, fjtirado commented
@mareknovotny The other occurrences  are already mentioned in the description (which I guess you missed). We need to discuss them. I cannot change the branch name in the code before the real branch name is changes or I will have an e-mail from you complaining about failed test.

2021-05-31 13:18 UTC, mareknovotny commented
my point is that whenever we prepared all here we can change branch name and merged it after that. @mbiarnes wdyt?

2021-06-01 07:51 UTC, fjtirado commented
@mareknovotny @lazarotti 
There are three exceptions documented here
https://issues.redhat.com/browse/BAPL-1990?focusedCommentId=16177600&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16177600
I think all of them can be accepted by PM. 
I do not think we should change branch name on GIT, or at least this is what I understood from this comment on the same bapl
https://issues.redhat.com/browse/BAPL-1990?focusedCommentId=16237547&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16237547
If finally we rename the branch name (I do not recommend that), in order to avoid failed test, I agree we should do that with this same JIRA 
For the other two exceptions, for the Karaf one I can not figure out an alternative other than not using that Karaf feature, which will probably break something, since I assume that exception is included there for a reason. Anyway, we can argue that the offensive language is in third party tool we have not control over. 
For getMasterBranch method, I think the suffix "branch" remove the offensive meaning of the word master, clearly indicating that in this context master is equivalent to main (changing that will break code using git work item)

2021-06-01 07:52 UTC, fjtirado commented
jenkins retest this

2021-06-02 17:13 UTC, fjtirado commented
jenkins retest this

2021-08-04 07:54 UTC, elguardian requested changes

2021-08-04 07:54 UTC, elguardian commented on ethereum-workitem/src/test/java/org/jbpm/process/workitem/ethereum/test/contract/Greeter.java
> + * <a href="https://github.com/web3j/web3j">codegen module</a> to update.
main insteado of master

2021-08-04 07:54 UTC, elguardian commented on ethereum-workitem/src/test/java/org/jbpm/process/workitem/ethereum/test/contract/Mortal.java
> + * <a href="https://github.com/web3j/web3j">codegen module</a> to update.
main instead of master

2021-08-05 11:47 UTC, elguardian approved these changes
LGTM

2021-08-06 10:55 UTC, elguardian commented
Jenkins retest this please

2021-08-09 06:48 UTC, merged